apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: deployment-sa
  namespace: default
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io
